### ISSUE TITLE
Intercode does not load under iOS 14.5.1

### ISSUE THREAD

**Issue by diewald** [neinteractiveliterature/intercode#5119]
I've tried to load the U site and the T site on my iPad. The page is blank. The tab says "Main Landin..." 

I will be updating to 14.6 shortly, but 14.5 had some big security changes.

**Comment by nbudin** [comment]
Hey @diewald, just wanted to check in on this - is this working now for you?  I mentioned on the Larp Library issue that I thought it should be working on Intercode, but since I was never able to repro it myself I want to check in with you before closing this.

**Comment by diewald** [comment]
It is still not working for me, even having upgraded to 14.6. I haven't had the chance to go to 14.7.1 yet, although that will only be for the iPad. 14.7.1 can brick cellular service on iPhones, apparently.

**Comment by nbudin** [comment]
@diewald Aw man!  I think this must be a different issue than the one we saw in Larp Library, because the check that was failing there doesn't even exist in Intercode.  could you do the same thing we did there with connecting it to a Mac running Safari and screenshot the developer tools?
